import * as XLSX from "xlsx";

export type ExcelRows = {
  name: string;
  rows: (string | number)[][];
};

const MAX_FILE_SIZE = 10 * 1024 * 1024;
const MAX_SHEETS = 20;
const MAX_ROWS_PER_SHEET = 10_000;
const MAX_COLUMNS_PER_ROW = 500;
const MAX_TOTAL_CELLS = 200_000;
const ALLOWED_EXTENSIONS = new Set(["xlsx", "xls"]);

class ExcelImportError extends Error {}

function reject(message: string): never {
  throw new ExcelImportError(message);
}

/**
 * Reads an employee-supplied workbook with the maintained SheetJS parser.
 * The styling fork is intentionally reserved for files generated by this app.
 */
export async function readExcelRows(file: File): Promise<ExcelRows[]> {
  const extension = file.name.split(".").pop()?.toLowerCase() ?? "";
  if (!ALLOWED_EXTENSIONS.has(extension)) {
    reject("Поддерживаются только файлы Excel .xlsx и .xls");
  }
  if (file.size > MAX_FILE_SIZE) {
    reject("Файл Excel слишком большой. Максимальный размер — 10 МБ");
  }

  try {
    const workbook = XLSX.read(await file.arrayBuffer(), {
      type: "array",
      dense: true,
      cellFormula: false,
      cellHTML: false,
      cellNF: false,
      cellStyles: false,
      bookVBA: false,
      sheetRows: MAX_ROWS_PER_SHEET + 1,
    });

    if (workbook.SheetNames.length > MAX_SHEETS) {
      reject(`В файле слишком много листов. Максимум — ${MAX_SHEETS}`);
    }

    let totalCells = 0;
    const sheets: ExcelRows[] = [];
    for (const name of workbook.SheetNames) {
      const sheet = workbook.Sheets[name];
      if (!sheet) continue;
      const reference = sheet["!fullref"] ?? sheet["!ref"];
      if (reference) {
        const range = XLSX.utils.decode_range(reference);
        const rowCount = range.e.r - range.s.r + 1;
        const columnCount = range.e.c - range.s.c + 1;
        if (rowCount > MAX_ROWS_PER_SHEET) {
          reject(`На листе «${name}» больше ${MAX_ROWS_PER_SHEET} строк`);
        }
        if (columnCount > MAX_COLUMNS_PER_ROW) {
          reject(`На листе «${name}» больше ${MAX_COLUMNS_PER_ROW} столбцов`);
        }
        totalCells += rowCount * columnCount;
        if (totalCells > MAX_TOTAL_CELLS) {
          reject(`В файле больше ${MAX_TOTAL_CELLS} обрабатываемых ячеек`);
        }
      }

      const rows = XLSX.utils.sheet_to_json<(string | number)[]>(sheet, {
        header: 1,
        raw: false,
        defval: "",
      });
      sheets.push({ name, rows });
    }
    return sheets;
  } catch (error) {
    if (error instanceof ExcelImportError) throw error;
    throw new Error("Не удалось прочитать Excel-файл. Проверьте, что он не повреждён");
  }
}
