[CmdletBinding()]
param(
  [string]$SupabaseUrl = "http://127.0.0.1:8000",
  [string]$SupabaseEnv = "D:\prog\ARV-Server\supabase\.env",
  [string]$OutputPath,
  [int]$Port = 3000
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $SupabaseEnv -PathType Leaf)) {
  throw "Supabase environment file not found: $SupabaseEnv"
}

$repositoryRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutputPath) {
  $OutputPath = Join-Path $repositoryRoot ".env"
}

$settings = @{}
foreach ($line in Get-Content -LiteralPath $SupabaseEnv) {
  if ($line -match "^(?<name>[A-Za-z_][A-Za-z0-9_]*)=(?<value>.*)$") {
    $settings[$Matches.name] = $Matches.value.Trim()
  }
}

$required = @("ANON_KEY")
$missing = @($required | Where-Object { -not $settings.ContainsKey($_) -or -not $settings[$_] })
if ($missing.Count -gt 0) {
  throw "Missing Supabase setting(s): $($missing -join ', ')"
}

if ($SupabaseUrl -notmatch "^https?://[^\s/]+(?::[0-9]+)?$") {
  throw "SupabaseUrl must be an HTTP(S) origin without a path: $SupabaseUrl"
}

$values = @($SupabaseUrl, $settings["ANON_KEY"])
if ($values | Where-Object { $_ -match "[`r`n]" }) {
  throw "Environment values must not contain line breaks."
}

$content = @(
  "# Generated by deploy/configure-local-env.ps1. Do not commit this file."
  "VITE_SUPABASE_URL=$SupabaseUrl"
  "SUPABASE_URL=$SupabaseUrl"
  "VITE_SUPABASE_PUBLISHABLE_KEY=$($settings['ANON_KEY'])"
  "SUPABASE_PUBLISHABLE_KEY=$($settings['ANON_KEY'])"
  "PORT=$Port"
)

$outputDirectory = Split-Path -Parent ([System.IO.Path]::GetFullPath($OutputPath))
if (-not (Test-Path -LiteralPath $outputDirectory -PathType Container)) {
  throw "Output directory not found: $outputDirectory"
}

$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($OutputPath, $content, $utf8WithoutBom)

Write-Host "Local application environment created: $OutputPath"
Write-Host "Supabase URL: $SupabaseUrl"
Write-Host "Application port: $Port"
Write-Host "The service-role key stays in the protected Supabase server file."
