/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedContractorsRouteImport } from './routes/_authenticated/contractors'
import { Route as AuthenticatedDashboardsRouteImport } from './routes/_authenticated/dashboards'
import { Route as AuthenticatedDepartmentRouteImport } from './routes/_authenticated/department'
import { Route as AuthenticatedEffortRouteImport } from './routes/_authenticated/effort'
import { Route as AuthenticatedInstructionRouteImport } from './routes/_authenticated/instruction'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedPersonPersonIdRouteImport } from './routes/_authenticated/person.$personId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractorsRoute =
  AuthenticatedContractorsRouteImport.update({
    id: '/contractors',
    path: '/contractors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsRoute = AuthenticatedDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentRoute = AuthenticatedDepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEffortRoute = AuthenticatedEffortRouteImport.update({
  id: '/effort',
  path: '/effort',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstructionRoute =
  AuthenticatedInstructionRouteImport.update({
    id: '/instruction',
    path: '/instruction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonPersonIdRoute =
  AuthenticatedPersonPersonIdRouteImport.update({
    id: '/person/$personId',
    path: '/person/$personId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/contractors': typeof AuthenticatedContractorsRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/department': typeof AuthenticatedDepartmentRoute
  '/effort': typeof AuthenticatedEffortRoute
  '/instruction': typeof AuthenticatedInstructionRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/roles': typeof AuthenticatedRolesRoute
  '/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/contractors': typeof AuthenticatedContractorsRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/department': typeof AuthenticatedDepartmentRoute
  '/effort': typeof AuthenticatedEffortRoute
  '/instruction': typeof AuthenticatedInstructionRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/': typeof AuthenticatedIndexRoute
  '/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contractors': typeof AuthenticatedContractorsRoute
  '/_authenticated/dashboards': typeof AuthenticatedDashboardsRoute
  '/_authenticated/department': typeof AuthenticatedDepartmentRoute
  '/_authenticated/effort': typeof AuthenticatedEffortRoute
  '/_authenticated/instruction': typeof AuthenticatedInstructionRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contractors'
    | '/dashboards'
    | '/department'
    | '/effort'
    | '/instruction'
    | '/projects'
    | '/roles'
    | '/person/$personId'
    | '/projects/$projectId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/contractors'
    | '/dashboards'
    | '/department'
    | '/effort'
    | '/instruction'
    | '/roles'
    | '/'
    | '/person/$personId'
    | '/projects/$projectId'
    | '/projects'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contractors'
    | '/_authenticated/dashboards'
    | '/_authenticated/department'
    | '/_authenticated/effort'
    | '/_authenticated/instruction'
    | '/_authenticated/projects'
    | '/_authenticated/roles'
    | '/_authenticated/'
    | '/_authenticated/person/$personId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contractors': {
      id: '/_authenticated/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof AuthenticatedContractorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards': {
      id: '/_authenticated/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthenticatedDashboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/department': {
      id: '/_authenticated/department'
      path: '/department'
      fullPath: '/department'
      preLoaderRoute: typeof AuthenticatedDepartmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/effort': {
      id: '/_authenticated/effort'
      path: '/effort'
      fullPath: '/effort'
      preLoaderRoute: typeof AuthenticatedEffortRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instruction': {
      id: '/_authenticated/instruction'
      path: '/instruction'
      fullPath: '/instruction'
      preLoaderRoute: typeof AuthenticatedInstructionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/person/$personId': {
      id: '/_authenticated/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof AuthenticatedPersonPersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContractorsRoute: typeof AuthenticatedContractorsRoute
  AuthenticatedDashboardsRoute: typeof AuthenticatedDashboardsRoute
  AuthenticatedDepartmentRoute: typeof AuthenticatedDepartmentRoute
  AuthenticatedEffortRoute: typeof AuthenticatedEffortRoute
  AuthenticatedInstructionRoute: typeof AuthenticatedInstructionRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPersonPersonIdRoute: typeof AuthenticatedPersonPersonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContractorsRoute: AuthenticatedContractorsRoute,
  AuthenticatedDashboardsRoute: AuthenticatedDashboardsRoute,
  AuthenticatedDepartmentRoute: AuthenticatedDepartmentRoute,
  AuthenticatedEffortRoute: AuthenticatedEffortRoute,
  AuthenticatedInstructionRoute: AuthenticatedInstructionRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPersonPersonIdRoute: AuthenticatedPersonPersonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
